# This configuration was used Ebert to review the elitau/pact_elixir repository
# on dc7d140f2177338f502d5116ea3182f19476dca4.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://docs.ebertapp.io/configuration and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- config
- test

