language: elixir
elixir: '1.6.0-rc.1'
otp_release: '20.0'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends rustc cargo
  - rustc --version
  - cargo --version

env: MIX_ENV=test

# Compiling PactMockServer outputs a warning {:error, {:upgrade, 'Upgrade not supported by this NIF library.'}} which
# swallows coverage results for it. Running test twice solves this for now.
script:
  - mix test
  - mix coveralls.travis

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report