language: elixir
elixir: '1.5.2'
otp_release: '20.0'

matrix:
  include:
    - language: rust
      rust: 1.21.0

before_install:
  - erl -version
  - elixir --version
  - mix --version
  - rustc --version
  - cargo --version
