language: elixir
elixir: '1.5.2'
otp_release: '20.0'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends rustc cargo
  - rustc --version
  - cargo --version

env: MIX_ENV=test

# TODO: not all files are reported to coveralls eg. PactMockServer is not there. Maybe the elixir version is the reason
# for this.
script: mix coveralls.travis