language: elixir
elixir: '1.5.2'
otp_release: '20.0'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends rustc cargo
  - rustc --version
  - cargo --version

env: MIX_ENV=test

script: mix coveralls.travis