[package]
name = "pactmockserver"
version = "0.1.0"
authors = []

[lib]
name = "pactmockserver"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.15.1"
libc = "0.2.9"
rustler_codegen = "0.15.1"
lazy_static = "0.2"

# TODO: Use official release after pull request xxx was merged
pact_mock_server = { git = "https://github.com/elitau/pact-reference" }
# version = "0.3.1", path = "../../../pact-reference/rust/pact_mock_server"
